version: '3.9'

services:
  db:
    image: postgres:15.3-alpine
    restart: always
    volumes:
      - db_data:/var/lib/postgresql/data
    env_file:
      - ../.env

  backend:
    image: k1n8/crm_app:latest
    restart: always
    volumes:
      - static_value:/crm_app/staticfiles/
    env_file:
      - ../.env
    depends_on:
      - db

  nginx:
    image: nginx:1.19.3-alpine
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - static_value:/var/html/staticfiles/
    depends_on:
      - backend

volumes:
  static_value:
  db_data:
