version: '3.9'

services:
  frontend:
    image: k1n8/crm_app:latest
    volumes:
      - ../frontend/:/frontend/result_build/

  db:
    image: postgres:15.3-alpine
    restart: always
    volumes:
      - db_data:/var/lib/postgresql/data
    env_file:
      - ../.env

  redis:
    image: redis:7.2-alpine
    restart: always
    ports:
      - "6379:6379"
    env_file:
      - ../.env
    depends_on:
      - db

  backend:
    image: k1n8/crm_app:latest
    restart: always
    volumes:
      - static_value:/crm_app/staticfiles/
    env_file:
      - ../.env
    depends_on:
      - db

  nginx:
    image: nginx:1.19.3-alpine
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ../frontend/build:/usr/share/nginx/html/
      - static_value:/var/html/staticfiles/
    depends_on:
      - backend

  worker:
    image: k1n8/crm_app:latest
    volumes:
      - static_value:/crm_app/staticfiles/
    env_file:
      - ../.env
    command: poetry run celery -A backend worker -l info
    depends_on:
      - redis
      - db
      - backend

  beat:
    image: k1n8/crm_app:latest
    volumes:
      - static_value:/crm_app/staticfiles/
    env_file:
      - ../.env
    command: poetry run celery -A backend beat -l info
    depends_on:
      - redis
      - db
      - backend

volumes:
  static_value:
  db_data:
