# Generated by Django 4.2.10 on 2024-03-03 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('merch', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='budget',
            options={'ordering': ('ambassador',)},
        ),
    ]
