# Generated by Django 4.2.10 on 2024-03-02 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merch', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='merchforsend',
            name='count',
            field=models.IntegerField(default=1),
        ),
    ]
