# Generated by Django 4.2.10 on 2024-02-24 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ambassadors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reg_date', models.DateField(verbose_name='дата регистрации')),
            ],
            options={
                'ordering': ('reg_date',),
            },
        ),
    ]
