# Generated by Django 4.2.10 on 2024-02-29 18:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ambassadors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ambassadors',
            name='supervisor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ambassador_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
