# Generated by Django 4.2.10 on 2024-03-02 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ambassadors', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ambassadors',
            name='status',
            field=models.CharField(choices=[('active', 'Активный'), ('pause', 'На паузе'), ('not_ambassador', 'Не амбассадор'), ('to_check', 'Уточняется')], max_length=14, null=True),
        ),
    ]
