# Generated by Django 4.2.10 on 2024-02-27 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ambassadors', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studyprogramm',
            name='title',
            field=models.CharField(max_length=300),
        ),
    ]
