# Generated by Django 4.2.10 on 2024-03-03 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ambassadors', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studyprogramm',
            options={'ordering': ('title',)},
        ),
    ]
