# Generated by Django 4.2.10 on 2024-02-23 17:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ambassadors', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudyProgramm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
            ],
        ),
        migrations.AlterField(
            model_name='ambassadors',
            name='supervisor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ambassador_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ambassadors',
            name='study_programm',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ambassador_programm', to='ambassadors.studyprogramm'),
        ),
    ]
