# Generated by Django 4.2.10 on 2024-02-24 10:13

import ambassadors.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ambassadors', '0003_studyprogramm_alter_ambassadors_supervisor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ambassadors',
            name='address',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='ambassadors',
            name='city',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='ambassadors',
            name='country',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='ambassadors',
            name='education',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='ambassadors',
            name='email',
            field=models.EmailField(max_length=150, unique=True),
        ),
        migrations.AlterField(
            model_name='ambassadors',
            name='job',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='ambassadors',
            name='name',
            field=models.CharField(max_length=150, verbose_name='имя'),
        ),
        migrations.AlterField(
            model_name='ambassadors',
            name='patronymic',
            field=models.CharField(max_length=150, null=True, verbose_name='отчество'),
        ),
        migrations.AlterField(
            model_name='ambassadors',
            name='promocode',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='ambassadors',
            name='surname',
            field=models.CharField(max_length=150, verbose_name='фамилия'),
        ),
        migrations.AlterField(
            model_name='ambassadors',
            name='telegram_handle',
            field=models.CharField(max_length=150, validators=[ambassadors.validators.validate_tg_handle]),
        ),
        migrations.AlterField(
            model_name='ambassadors',
            name='want_to_do',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='studyprogramm',
            name='title',
            field=models.CharField(max_length=150),
        ),
    ]
