# Generated by Django 4.2.10 on 2024-02-24 08:59

import ambassadors.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ambassadors', '0003_studyprogramm_alter_ambassadors_supervisor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ambassadors',
            name='phone',
            field=models.CharField(max_length=12, unique=True, validators=[ambassadors.validators.validate_phone]),
        ),
    ]
