# Generated by Django 4.2.10 on 2024-02-25 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ambassadors', '0004_alter_ambassadors_address_alter_ambassadors_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ambassadors',
            name='date_created',
            field=models.DateField(auto_now_add=True, verbose_name='дата регистрации'),
        ),
    ]
