# Generated by Django 4.2.10 on 2024-02-24 09:33

import ambassadors.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ambassadors', '0004_alter_ambassadors_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ambassadors',
            name='phone',
            field=models.CharField(max_length=13, unique=True, validators=[ambassadors.validators.validate_phone]),
        ),
    ]
